CREATE TABLE "RDADMIN"."CREDENTIALS" (CREDENTIALSKEY NUMBER(38) PRIMARY KEY NOT NULL, EMPLOYEEKEY NUMBER (38) NOT NULL, USERNAME VARCHAR2(30) NOT NULL UNIQUE, PASSWORD VARCHAR2(16) NOT NULL, LASTLOGGEDIN DATE NOT NULL, ACTSTATUS VARCHAR2(1) NOT NULL, LOGINSTATUS VARCHAR2(1) NOT NULL, EXPIREDATE DATE NOT NULL, CONSTRAINT  EMPLOYEEKEY_FK FOREIGN KEY (EMPLOYEEKEY) REFERENCES EMPLOYEE(EMPLOYEEKEY));

CREATE SEQUENCE "RDADMIN".CREDENTIALS_SEQ  MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."EMPLOYEE" (EMPLOYEEKEY NUMBER(38) NOT NULL PRIMARY KEY, FIRSTNAME VARCHAR2(100) NOT NULL, LASTNAME VARCHAR2(100) NOT NULL, GENDER VARCHAR2(1) NOT NULL, DESIGNATION VARCHAR2(100) NOT NULL, CONTACTKEY NUMBER(38) NOT NULL, ADDRESSKEY NUMBER(38) NOT NULL);

CREATE SEQUENCE "RDADMIN".EMPLOYEE_SEQ  MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE SEQUENCE "RDADMIN".JOBDETAILS_SEQ  MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."JOBDETAILS" (JOBKEY NUMBER(38) PRIMARY KEY NOT NULL, JOBNUMBER VARCHAR2(12 CHAR), CLIENTKEY NUMBER(38) NOT NULL,PATIENTNAME VARCHAR2(150 CHAR),TOOTHNUMBER VARCHAR2(100 CHAR) NOT NULL,JOBTYPEKEY NUMBER(38) NOT NULL,SHADE VARCHAR2(2 CHAR) NOT NULL,UNITPRICE NUMBER(38,2) NOT NULL,UNIT NUMBER(5) NOT NULL,DELIVERYDATE DATE,RECEIVEDDATE DATE NOT NULL,AMOUNT NUMBER(38,2) NOT NULL,PRICEDESC VARCHAR2(100 CHAR),DRCOMMENTS VARCHAR2(1000 CHAR),TECHCOMMENTS VARCHAR2(1000 CHAR),STATUS VARCHAR2(2 CHAR));

CREATE SEQUENCE "RDADMIN"."ADDRESS_SEQ" MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."ADDRESS" (ADDRESSKEY NUMBER(38) PRIMARY KEY NOT NULL,ADDRESSLINE1 VARCHAR2(100 CHAR) NOT NULL,ADDRESSLINE2 VARCHAR2(100 CHAR), CITY VARCHAR2(50 CHAR) NOT NULL,  STATE VARCHAR2(50 CHAR) NOT NULL, COUNTRY VARCHAR2(2 CHAR) DEFAULT 'IN',  POSTALCODE VARCHAR2(6 CHAR) DEFAULT '700099');

CREATE SEQUENCE "RDADMIN"."CONTACT_SEQ" MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."CONTACT" (CONTACTKEY NUMBER(38) PRIMARY KEY NOT NULL,MOBILENUMBER VARCHAR2(12 CHAR),PHONENUMBER VARCHAR2(15 CHAR),FAX VARCHAR2(15 CHAR),EMAILID VARCHAR2(150 CHAR));

CREATE SEQUENCE "RDADMIN"."CLIENT_SEQ" MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."CLIENT" (CLIENTKEY NUMBER(38) PRIMARY KEY NOT NULL,HOSPITALNAME VARCHAR2(50 CHAR), TITLE VARCHAR2(2 CHAR),FIRSTNAME VARCHAR2(150 CHAR) NOT NULL,LASTNAME VARCHAR2(50 CHAR),GENDER VARCHAR2(1 CHAR),ADDRESSKEY NUMBER(38),CONTACTKEY NUMBER(38) NOT NULL, CONSTRAINT FK_ADD FOREIGN KEY (ADDRESSKEY) REFERENCES ADDRESS(ADDRESSKEY), CONSTRAINT FK_CONT FOREIGN KEY (CONTACTKEY) REFERENCES CONTACT(CONTACTKEY));

CREATE SEQUENCE "RDADMIN"."JOBTYPE_SEQ" MINVALUE 100  MAXVALUE 999999999999999999  START WITH 100  INCREMENT BY 1  CACHE 100;

CREATE TABLE "RDADMIN"."JOBTYPE" (JOBTYPEKEY NUMBER(38) PRIMARY KEY NOT NULL,JOBTYPENAME VARCHAR2(10 CHAR) NOT NULL,DESCRIPTION VARCHAR2(50 CHAR),UNITPRICE NUMBER(38,2) NOT NULL);

CREATE TABLE "RDADMIN"."CLIENTSJOBTYPE" (JOBTYPEKEY NUMBER(38) NOT NULL,CLIENTKEY NUMBER(38) NOT NULL,UNITPRICE NUMBER(38,2) NOT NULL, CONSTRAINT FK_JOBKEY FOREIGN KEY(JOBTYPEKEY) REFERENCES JOBTYPE(JOBTYPEKEY),CONSTRAINT FK_CLIENTKEY FOREIGN KEY(CLIENTKEY) REFERENCES CLIENT(CLIENTKEY));



insert into JOBDETAILS (JOBNUMBER,CLIENTKEY,PATIENTNAME,TOOTHNUMBER,JOBTYPEKEY,SHADE,UNITPRICE,UNIT,DELIVERYDATE,RECEIVEDDATE,AMOUNT,PRICEDESC,DRCOMMENTS,TECHCOMMENTS,STATUS)
values(JOBDETAILS_SEQ.NEXTVAL,123,'hello','LL153',2,'A2',550,5,sysdate+2,sysdate,2750,'price desc','doc comments','tech comments','NW');

insert into EMPLOYEE  (EMPLOYEEKEY,FIRSTNAME,LASTNAME,GENDER,DESIGNATION,CONTACTKEY,ADDRESSKEY) values (EMPLOYEE_SEQ.nextval,'Kinkuraj','Sahoo','M','Admin',1,1);

DROP TABLE CREDENTIALS;
select * from EMPLOYEE;
select * from CREDENTIALS;
select * from jobdetails;
insert into CREDENTIALS  values (CREDENTIALS_SEQ.nextval,100,'raj','raj',sysdate,'A','A',sysdate);